const SearchConvertStoreBase = new Map<string, string>();

SearchConvertStoreBase.set('앚', '아이즈원');
SearchConvertStoreBase.set('앚온미', 'EYES ON ME');
SearchConvertStoreBase.set('쇼콘', 'SHOW CON');
SearchConvertStoreBase.set('뮤뱅', '뮤직뱅크');
SearchConvertStoreBase.set('음중', '음악중심');
SearchConvertStoreBase.set('인가', '인기가요');
SearchConvertStoreBase.set('아시안', 'Asian');
SearchConvertStoreBase.set('아티스트', 'Artist');
SearchConvertStoreBase.set('어워드', 'Award');
SearchConvertStoreBase.set('어워즈', 'Awards');
SearchConvertStoreBase.set('마마', 'MAMA');
SearchConvertStoreBase.set('엠넷', 'Mnet');
SearchConvertStoreBase.set('코리아', 'KOREA');
SearchConvertStoreBase.set('홍콩', 'HONGKONG');
SearchConvertStoreBase.set('재팬', 'JAPAN');
SearchConvertStoreBase.set('Golden', '골든');
SearchConvertStoreBase.set('Disk', '디스크');
SearchConvertStoreBase.set('골디', '골든디스크');
SearchConvertStoreBase.set('서가대', '서울가요대상');
SearchConvertStoreBase.set('Seoul Music', '서울가요');
SearchConvertStoreBase.set('Seoul Music Award', '서울가요대상');
SearchConvertStoreBase.set('Seoul Music Awards', '서울가요대상');
SearchConvertStoreBase.set('Showcase', '쇼케이스');
SearchConvertStoreBase.set('Debut', '데뷔');
SearchConvertStoreBase.set('Gaon', '가온');
SearchConvertStoreBase.set('Chart', '차트');
SearchConvertStoreBase.set('후지', 'Fuji');
SearchConvertStoreBase.set('티비', 'TV');
SearchConvertStoreBase.set('아베마', 'Abema');
SearchConvertStoreBase.set('아사히', 'Asahi');
SearchConvertStoreBase.set('아사이', 'Asahi');
SearchConvertStoreBase.set('버즈', 'BUZZ');
SearchConvertStoreBase.set('리듬', 'RHYTHM');
SearchConvertStoreBase.set('스페셜', 'Special');
SearchConvertStoreBase.set('파티', 'party');
SearchConvertStoreBase.set('하트', 'HEART');
SearchConvertStoreBase.set('하트아이즈', 'HEART*IZ');
SearchConvertStoreBase.set('컬러아이즈', 'COLOR*IZ');
SearchConvertStoreBase.set('블룸아이즈', 'BLOOM*IZ');
SearchConvertStoreBase.set('블룸', 'BLOOM');
SearchConvertStoreBase.set('컬러', 'COLOR');
SearchConvertStoreBase.set('컴백', 'COMEBACK');
SearchConvertStoreBase.set('음방', '음악방송');
SearchConvertStoreBase.set('환상일기', 'Oneiric Diary');
SearchConvertStoreBase.set('오나이릭', 'Oneiric');
SearchConvertStoreBase.set('오나이릭다이어리', 'Oneiric Diary');
SearchConvertStoreBase.set('원릴러', 'One-reeler');
SearchConvertStoreBase.set('케이콘', 'KCON');
SearchConvertStoreBase.set('광주', 'GWANGJU');
SearchConvertStoreBase.set('스테이션', 'STATION');
SearchConvertStoreBase.set('페어', 'FAIR');
SearchConvertStoreBase.set('므금마', 'MGMA');
SearchConvertStoreBase.set('지니', 'Genie');
SearchConvertStoreBase.set('케이팝', 'K-POP');
SearchConvertStoreBase.set('아이치', 'AICHI');
SearchConvertStoreBase.set('임팩트', 'IMPACT');
SearchConvertStoreBase.set('마린', 'Marine');
SearchConvertStoreBase.set('맛세', 'Messe');
SearchConvertStoreBase.set('마세', 'Messe');
SearchConvertStoreBase.set('후쿠오카', 'Fukuoka');
SearchConvertStoreBase.set('사이타마', 'Saitama');
SearchConvertStoreBase.set('슈퍼', 'Super');
SearchConvertStoreBase.set('아레나', 'Arena');
SearchConvertStoreBase.set('위드', 'with');
SearchConvertStoreBase.set('택트', 'TACT');
SearchConvertStoreBase.set('온택트', 'ON:TACT');
SearchConvertStoreBase.set('Sori', '소리');
SearchConvertStoreBase.set('Bada', '바다');
SearchConvertStoreBase.set('Best', '베스트');
SearchConvertStoreBase.set('시어터', 'THEATER');
SearchConvertStoreBase.set('씨어터', 'THEATER');
SearchConvertStoreBase.set('수퍼', 'Super');
SearchConvertStoreBase.set('더블유', 'W');
SearchConvertStoreBase.set('스키토', 'Suki To');
SearchConvertStoreBase.set('이와세타이', 'Iwasetai');
SearchConvertStoreBase.set('스키토이와세타이', 'Suki To Iwasetai');
SearchConvertStoreBase.set('뱀파이어', 'Vampire');
SearchConvertStoreBase.set('부에노스', 'Buenos');
SearchConvertStoreBase.set('아이레스', 'Aires');
SearchConvertStoreBase.set('아이리스', 'Aires');
SearchConvertStoreBase.set('부에노', 'Buenos');
SearchConvertStoreBase.set('스키토', 'Suki To');
SearchConvertStoreBase.set('부에노스 아이레스', 'Buenos Aires');
SearchConvertStoreBase.set('부에노스 아이리스', 'Buenos Aires');
SearchConvertStoreBase.set('트웰브', 'Twelve');
SearchConvertStoreBase.set('아돌라', 'U+ IDOL LIVE');
SearchConvertStoreBase.set('마이크', 'MIC');
SearchConvertStoreBase.set('마이크온', 'MIC ON');
SearchConvertStoreBase.set('아이돌', 'IDOL');
SearchConvertStoreBase.set('라이브', 'LIVE');
SearchConvertStoreBase.set('멜뮤', 'MMA');
SearchConvertStoreBase.set('멜론', 'Melon');
SearchConvertStoreBase.set('프리미어', 'Premire');
SearchConvertStoreBase.set('선공개', 'Premire');
SearchConvertStoreBase.set('The fact', '더팩트');
SearchConvertStoreBase.set('The fact music', '더팩트 뮤직');
SearchConvertStoreBase.set('The face music awards', '더팩트 뮤직 어워즈');
SearchConvertStoreBase.set('유니버스', 'UNIVERSE');
SearchConvertStoreBase.set('유니콘', 'UNI-KON');
SearchConvertStoreBase.set('팬파티', 'FAN PARTY');
SearchConvertStoreBase.set('원더스토리', 'ONE, THE STORY');
SearchConvertStoreBase.set('일차', 'DAY');
SearchConvertStoreBase.set('히든스쿨', 'HIDDEN SCHOOL');
SearchConvertStoreBase.set('판타스틱', 'FANTASTIC');
SearchConvertStoreBase.set('판타스틱아이즈', 'FANTASTIC*IZ');
SearchConvertStoreBase.set('판타스틱앚', 'FANTASTIC*IZ');
SearchConvertStoreBase.set('컴백쇼', 'COMEBACK SHOW');
SearchConvertStoreBase.set('밍중', '음악중심');
SearchConvertStoreBase.set('민주중심', '음악중심');
SearchConvertStoreBase.set('댕댕가요', '인기가요');
SearchConvertStoreBase.set('유진가요', '인기가요');
SearchConvertStoreBase.set('녕직뱅크', '뮤직뱅크');
SearchConvertStoreBase.set('원영뱅크', '뮤직뱅크');
SearchConvertStoreBase.set('온콘', '온라인 콘서트');
SearchConvertStoreBase.set('잠실콘', 'EYES ON ME IN SEOUL');
SearchConvertStoreBase.set('서울콘', 'EYES ON ME IN SEOUL');
SearchConvertStoreBase.set('설콘', 'EYES ON ME IN SEOUL');
SearchConvertStoreBase.set('첫콘', 'EYES ON ME IN SEOUL');
SearchConvertStoreBase.set('오프콘', 'EYES ON ME IN SEOUL');
SearchConvertStoreBase.set('막콘', 'ONE, THE STORY');
SearchConvertStoreBase.set('chu', '아이즈원 츄');
SearchConvertStoreBase.set('fantasy', '환상');
SearchConvertStoreBase.set('season', '시즌');
SearchConvertStoreBase.set('히든', 'Hidden');
SearchConvertStoreBase.set('스쿨', 'School');
SearchConvertStoreBase.set('시즌 2', '비밀친구');
SearchConvertStoreBase.set('시즌 3', '환상캠퍼스');
SearchConvertStoreBase.set('시즌 4', 'ON:TACT');
SearchConvertStoreBase.set('izone chu', '아이즈원 츄');
SearchConvertStoreBase.set('iz chu', '아이즈원 츄');
SearchConvertStoreBase.set('eating', '잇힝');
SearchConvertStoreBase.set('trip', '트립');

const SearchConvertStore = new Map<string, string>();
const keys = [...SearchConvertStoreBase.keys()].sort((a, b) => b.length - a.length);
for (const key of keys) SearchConvertStore.set(key, SearchConvertStoreBase.get(key)!);

export default SearchConvertStore;
